<?xml version="1.0" ?>
<!DOCTYPE writers [
<!ELEMENT writers (EnglishLanguage)>
<!ELEMENT EnglishLanguage (fiction)>
<!ELEMENT fiction (pen)>
<!ELEMENT pen (name+)>
<!ELEMENT name (#PCDATA)>
]>           
<writers>
   <EnglishLanguage>
      <fiction>
         <pen>
            <name>Jane Austin</name>
            <name>Rex Stout</name>
            <name>Dashiell Hammett</name>
         </pen>
      </fiction>
   </EnglishLanguage>
</writers>